### ISSUE TITLE
The "Index" is contextual and changes depending on what is selected, displayed

### ISSUE THREAD

**Issue by BendixSpring** [TeamMentor/Master#952] opened 2015-03-24 18:06 UTC
This is potentially confusing.  I was expecting the index to be a static page of keywords.  That's typically what an index is.

It might be a good idea to have a high level "Static Index" that doesn't change, but using a "Topical Index" when filters are used.  I person could flip back to the Static index when clicking the Index button.

This is probably a topic for more discussion.

**Comment by roman87** [comment] 2015-03-29 22:41
We were expecting an issue like that :). Unfortinately there is a bug with the POC pages. Once it is fixed I will show you a page where the index does not change. The problem is that not all the articles that exists for say .NET filter. So for example if you select .NET, there may not be any articles for say Code Integrity articles. So we update the count to 0. It ends up looking quite ugly. 

I honestly don't see a point in a static index, like the back of the book index. There are going to be quite a few words there and it will be really impossible for someone to browse it. What if we change the word Index to say  "Directory" would that make things more intuative?

**Comment by BendixSpring** [comment] 2015-03-30 15:20
There is something to be said to NOT show topics that don't have content.  It makes it easier for people to find what they are looking for (Important design goal IMO).

"Index" implies a list of topics, like at the end of a book. I think having a "Full Index" of all topics would be a good choice if the user wanted to select that.  You can also default to an "Abbreviated Index" that would list the most common/popular topics.

**Comment by roman87** [comment] 2015-04-20 05:01
TTL expired. Closing this question.

**Closed by roman87** 2015-04-20 05:01 UTC
Labels: Type: Question
